// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlcjdegooxxitniotprn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsY2pkZWdvb3h4aXRuaW90cHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTQ2MTAsImV4cCI6MjA2OTg5MDYxMH0.ooD_XMR_eBuZLZM5W_btlgh9bphzPwkL-lFjr2HJkfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});